// Loads data/drop-rates.json — per-boss rare-drop tables pulled from the
// OSRS Wiki by scripts/build-drop-rates.mjs. The /next engine uses it to
// convert a player's Hiscores boss-KC into an expected-uniques readout
// ("142 Vorkath KC ≈ 0.85 visages expected, 0.05 Vorki pet chance").
//
// Server-side only — keeps the JSON off the client bundle.

import { readFile } from "node:fs/promises";
import { join } from "node:path";

export interface DropEntry {
  name: string;
  num: number;       // numerator of the rarity fraction
  denom: number;     // denominator
  rarity: string;    // "1/5000", "2/150" — original Wiki form, for display
}

export interface BossDropTable {
  hiscoresName: string;     // matches the OSRS Hiscores activity name
  drops: DropEntry[];       // sorted rarest first
}

let cache: Map<string, BossDropTable> | null = null;
let loading: Promise<Map<string, BossDropTable>> | null = null;

async function load(): Promise<Map<string, BossDropTable>> {
  // Two sources merged. The main file is generated by
  // scripts/build-drop-rates.mjs (Wiki-scraped, covers solo bosses well).
  // The raids file is hand-curated because the Wiki's CoX/ToB/ToA tables
  // are raid-team-dependent and don't lend themselves to scraping; for
  // those three raids we use 1-player effective rates instead.
  const mainPath = join(process.cwd(), "data", "drop-rates.json");
  const raidsPath = join(process.cwd(), "data", "drop-rates-raids.json");
  const [mainRaw, raidsRaw] = await Promise.all([
    readFile(mainPath, "utf8"),
    readFile(raidsPath, "utf8").catch(() => "{}")
  ]);
  const parsed = JSON.parse(mainRaw) as Record<string, BossDropTable>;
  const raids = JSON.parse(raidsRaw) as Record<string, BossDropTable | { _comment?: string }>;
  const m = new Map<string, BossDropTable>();
  for (const [k, v] of Object.entries(parsed)) m.set(k, v);
  for (const [k, v] of Object.entries(raids)) {
    if (k.startsWith("_")) continue; // skip metadata fields like "_comment"
    m.set(k, v as BossDropTable);
  }
  return m;
}

export async function getDropRates(): Promise<Map<string, BossDropTable>> {
  if (cache) return cache;
  if (loading) return loading;
  loading = load().then((m) => {
    cache = m;
    loading = null;
    return m;
  });
  return loading;
}
