import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { copyLabelForDevStep, PLUGIN_DEV_STEPS } from "@/lib/plugin-install";
import { LOCAL_SYNC_CLAIM_URL, LOCAL_SYNC_URL } from "@/lib/plugin-sync-actions";
import { pluginContextFromSearchParams, pluginHeroActions, shouldShowReleaseHandoff } from "@/app/plugin/page";
import type { PluginHubReviewReadiness } from "@/lib/plugin-hub-status";

describe("plugin page copy constants", () => {
  it("keeps developer sync endpoints explicit and local", () => {
    expect(LOCAL_SYNC_URL).toContain("/api/sync");
    expect(LOCAL_SYNC_CLAIM_URL).toBe(`${LOCAL_SYNC_URL}/claim`);
  });

  it("keeps the developer install flow complete and ordered", () => {
    expect(PLUGIN_DEV_STEPS.map((step) => step.label)).toEqual(["1", "2", "3", "4"]);
    expect(PLUGIN_DEV_STEPS.map((step) => step.code)).toContain(LOCAL_SYNC_URL);
    expect(PLUGIN_DEV_STEPS.map((step) => step.code)).toContain(LOCAL_SYNC_CLAIM_URL);
  });

  it("uses URL copy labels for endpoints and command labels for shell commands", () => {
    const syncStep = PLUGIN_DEV_STEPS.find((step) => step.code === LOCAL_SYNC_URL);
    const runStep = PLUGIN_DEV_STEPS.find((step) => step.code.startsWith("npm run dev"));

    expect(syncStep && copyLabelForDevStep(syncStep)).toBe("Copy URL");
    expect(runStep && copyLabelForDevStep(runStep)).toBe("Copy command");
  });

  it("keeps player-facing plugin setup explicit about sync opt-in", () => {
    const pageSource = readFileSync(join(process.cwd(), "src/app/plugin/page.tsx"), "utf8");

    expect(pageSource).toContain("Enable sync");
    expect(pageSource).toContain("Auto-sync on login");
    expect(pageSource).toContain("does not POST progress until you enable");
    expect(pageSource).toContain("checkSummary");
    expect(pageSource).toContain("submittedCommit");
    expect(pageSource).toContain("pinSummary");
    expect(pageSource).toContain("reviewSummary");
    expect(pageSource).toContain('reviewSummary.includes("requested changes")');
    expect(pageSource).toContain('reviewSummary.includes("approval recorded")');
    expect(pageSource).toContain("reviewCopySummary");
    expect(pageSource).toContain("reviewCopyIssues");
    expect(pageSource).toContain("pluginHubReviewReadiness(pluginHubStatus)");
    expect(pageSource).toContain("PluginReviewReadinessCard");
    expect(pageSource).toContain("pluginHubMaintainerReviewGate(pluginHubStatus)");
    expect(pageSource).toContain("MaintainerReviewGateCard");
    expect(pageSource).toContain("Maintainer review gate");
    expect(pageSource).toContain('id="review-readiness"');
    expect(pageSource).toContain("Plugin Hub install readiness");
    expect(pageSource).toContain("Normal players should stay on web recommendations until this card says Plugin Hub install can be advertised.");
    expect(pageSource).toContain("reviewReadiness.playerInstallReady");
    expect(pageSource).toContain("Live PR body still");
    expect(pageSource).toContain('reviewCopySummary.startsWith("Live PR body still")');
    expect(pageSource).toContain("ReviewCopyBlockerCard");
    expect(pageSource).toContain("PR body blocking review");
    expect(pageSource).toContain("reviewers still see stale submission text");
    expect(pageSource).toContain("Even when the submitted commit is correct");
    expect(pageSource).toContain("REVIEW_COPY_FIXES");
    expect(pageSource).toContain("Exact replacement intent");
    expect(pageSource).toContain("Auto-sync on login defaults off and no progress POST happens until the player opts in.");
    expect(pageSource).toContain("raw install token is sent only as Authorization bearer");
    expect(pageSource).toContain("sync POSTs only after opt-in");
    expect(pageSource).toContain("Sync on quest complete defaults off and is gated behind Auto-sync on login.");
    expect(pageSource).toContain("the opt-in payload includes Slayer task, streak, points and block-list state.");
    expect(pageSource).toContain("bank, inventory, equipment, GE offers and wealth are never sent by the plugin.");
    expect(pageSource).toContain("Replace with the canonical PR body generated by Scapestack.");
    expect(pageSource).toContain("npm run --silent plugin:pr-body -- --offline");
    expect(pageSource).toContain("standaloneCommit");
    expect(pageSource).toContain("Local release handoff");
    expect(pageSource).toContain("Plugin Hub pin");
    expect(pageSource).toContain("Data contract");
    expect(pageSource).toContain("Sent after opt-in");
    expect(pageSource).toContain("Never sent");
    expect(pageSource).toContain("No credentials");
    expect(pageSource).toContain("Plugin version");
    expect(pageSource).toContain("Player install path");
    expect(pageSource).toContain("Developer / tester install");
    expect(pageSource).toContain("for testers and developers only");
    expect(pageSource).toContain("side-load path is only for testers");
    expect(pageSource).toContain("not visible to RuneLite reviewers");
    expect(pageSource).toContain("Review risk");
    expect(pageSource).toContain("plugin:release-check:live");
    expect(pageSource).toContain("RuneLite reviewer packet");
    expect(pageSource).toContain("Copy reviewer packet");
    expect(pageSource).toContain("buildPluginReviewerReplyCommand()");
    expect(pageSource).toContain("reviewerReplyCommand");
    expect(pageSource).toContain("Maintainer reply handoff");
    expect(pageSource).toContain("Copy reviewer reply command");
    expect(pageSource).toContain("without opening Scapestack");
    expect(pageSource).toContain("PR body replacement");
    expect(pageSource).toContain('id="pr-body-fix"');
    expect(pageSource).toContain("scroll-mt-24");
    expect(pageSource).toContain("Copy PR body replacement");
    expect(pageSource).toContain("buildPluginPrBodyUpdateCommand()");
    expect(pageSource).toContain("buildPluginReviewerHandoffCommand()");
    expect(pageSource).toContain("Copy PR update command");
    expect(pageSource).toContain("GitHub auth prerequisite");
    expect(pageSource).toContain("gh auth login -h github.com");
    expect(pageSource).toContain("Copy GitHub auth login");
    expect(pageSource).toContain("PR body only");
    expect(pageSource).toContain("Full reviewer handoff");
    expect(pageSource).toContain("Copy full handoff command");
    expect(pageSource).toContain("reviewerHandoffCommand");
    expect(pageSource).toContain("handoffCommand={reviewerHandoffCommand}");
    expect(pageSource).toContain("generate the canonical PR body and reviewer packet");
    expect(pageSource).toContain("then add the maintainer comment in one command");
    expect(pageSource).toContain("updateCommand={prBodyUpdateCommand}");
    expect(pageSource).toContain("Final live gate");
    expect(pageSource).toContain("Copy final live gate");
    expect(pageSource).toContain("Do not present Plugin Hub install as ready until it prints");
    expect(pageSource).toContain("live-status replacement body");
    expect(pageSource).toContain("Run it only from an authenticated GitHub checkout");
    expect(pageSource).toContain("buildPluginPrBodyReplacement(pluginHubStatus)");
    expect(pageSource).toContain("background-thread HTTP");
    expect(pageSource).toContain("game integrity");
    expect(pageSource).toContain("read-only game integrity");
    expect(pageSource).toContain("Review fix first");
    expect(pageSource).toContain("Update the GitHub PR body first: the live text still says auto-sync defaults on.");
    expect(pageSource).toContain("Replace the token paragraph before review");
    expect(pageSource).toContain("Then add the reviewer packet as a short maintainer reply");
    expect(pageSource).toContain("Replace stale PR-body copy");
    expect(pageSource).toContain("PR_BODY_CORRECTIONS");
    expect(pageSource).toContain("Auto-sync on login defaults off.");
    expect(pageSource).toContain("Sync on quest complete defaults off.");
    expect(pageSource).toContain("No progress POST happens until the player opts in");
    expect(pageSource).toContain("The opt-in payload includes quest, diary, collection-log and Slayer task state.");
    expect(pageSource).toContain("Replace the old capture list before review");
    expect(pageSource).toContain("the shipped opt-in payload now includes Slayer task, streak, points and block-list state.");
    expect(pageSource).toContain("sent only as an Authorization bearer");
    expect(pageSource).toContain("Scapestack stores sha256(token)");
    expect(pageSource).toContain("/next becomes account-aware");
    expect(pageSource).toContain("Success includes the verified /next link");
    expect(pageSource).toContain("RuneLite chat hands you the verified /next URL");
    expect(pageSource).not.toContain("Success includes the exact /next link");
    expect(pageSource).not.toContain("RuneLite chat hands you the exact /next URL");
    expect(pageSource).toContain("PluginContextBanner");
    expect(pageSource).toContain("You came from /next to verify sync");
    expect(pageSource).toContain("Verify payload");
    expect(pageSource).toContain("pluginHeroActions(reviewReadiness, pluginHubStatus)");
    expect(pageSource).toContain("Plugin next actions");
    expect(pageSource).toContain("HeroActionLink");
    expect(pageSource).toContain("Fix review handoff first");
    expect(pageSource).toContain("Reviewer path first");
    expect(pageSource).toContain("Player path today");
    expect(pageSource).toContain("Tester path stays below");
    expect(pageSource).toContain("Player path: install from RuneLite");
    expect(pageSource).toContain("PLUGIN_VERIFY_SYNC_HASH");
    expect(pageSource).toContain("You came from this profile");
    expect(pageSource).toContain("Plugin Hub review is still pending");
    expect(pageSource).toContain("After /next loads the verified payload, it labels quest, diary, collection-log and Slayer coverage as verified, partial or missing.");
    expect(pageSource).not.toContain("Scapestack replaces guesswork with exact quest, diary, collection-log and Slayer signals.");
    expect(pageSource).toContain("Verify sync payload");
    expect(pageSource).toContain("PLUGIN_VERIFY_SYNC_HASH");
    expect(pageSource).not.toContain("Try /next now");
    expect(pageSource).toContain("Verified account state");
    expect(pageSource).toContain("a verified RuneLite payload turns it into a real OSRS copilot");
    expect(pageSource).toContain("verified RuneLite Plugin Hub payloads for coverage labels");
    expect(pageSource).not.toContain("verified RuneLite Plugin Hub payloads for exact account state");
    expect(pageSource).not.toContain("Exact account state,\n              <span");
    expect(pageSource).not.toContain("the RuneLite sync turns it into a real OSRS copilot");
    expect(pageSource).not.toContain("RuneLite Plugin Hub sync for exact account state");
    expect(pageSource).not.toContain("Current local build");
  });

  it("makes plugin hero CTAs match install readiness instead of one static verify button", () => {
    const status = { url: "https://github.com/runelite/plugin-hub/pull/12227" };
    const installable: PluginHubReviewReadiness = {
      state: "installable",
      tone: "good",
      label: "Plugin Hub install can be advertised",
      detail: "Ready.",
      blockers: [],
      playerInstallReady: true
    };
    const reviewBlocked: PluginHubReviewReadiness = {
      state: "review-blocked",
      tone: "warning",
      label: "Review handoff is not clean yet",
      detail: "Blocked.",
      blockers: ["PR body: token transport"],
      playerInstallReady: false
    };
    const pending: PluginHubReviewReadiness = {
      state: "pending-review",
      tone: "accent",
      label: "Ready for maintainer review, not player install",
      detail: "Pending.",
      blockers: ["Awaiting RuneLite maintainer review"],
      playerInstallReady: false
    };

    expect(pluginHeroActions(installable, status)).toEqual([
      {
        id: "verify",
        label: "Verify sync payload",
        href: "#verify-sync",
        kind: "primary"
      },
      {
        id: "live-pr",
        label: "View live PR status",
        href: status.url,
        kind: "secondary",
        external: true
      }
    ]);
    expect(pluginHeroActions(reviewBlocked, status)).toEqual([
      {
        id: "review-fix",
        label: "Fix review handoff first",
        href: "#pr-body-fix",
        kind: "primary"
      },
      {
        id: "web-next",
        label: "Use web recommendations",
        href: "/next?from=plugin&bank=none",
        kind: "secondary",
        usesNextHandoff: true
      }
    ]);
    expect(pluginHeroActions(pending, status)).toEqual([
      {
        id: "web-next",
        label: "Use web recommendations",
        href: "/next?from=plugin&bank=none",
        kind: "primary",
        usesNextHandoff: true
      },
      {
        id: "live-pr",
        label: "Track Plugin Hub review",
        href: status.url,
        kind: "secondary",
        external: true
      }
    ]);
  });

  it("keeps plugin page return context for /next refresh flows", () => {
    const context = pluginContextFromSearchParams({
      from: "next",
      rsn: "Lynx Titan",
      bank: "none"
    });

    expect(context).toEqual({
      title: "You came from /next to verify sync",
      body: "Run the sync checker on this page first. Return to /next only after it finds a verified payload for the same RSN.",
      cta: "Return to /next",
      href: "/next?rsn=Lynx+Titan&bank=none&from=plugin"
    });
    expect(context?.href).not.toContain("source=plugin-sync");
  });

  it("preserves bankless return context for other plugin handoffs", () => {
    const context = pluginContextFromSearchParams({
      from: "slayer",
      rsn: "Lynx Titan",
      bank: "none"
    });

    expect(context?.href).toBe("/slayer?rsn=Lynx+Titan&bank=none&from=plugin");
  });

  it("returns profile handoffs to the player profile route", () => {
    const context = pluginContextFromSearchParams({
      from: "profile",
      rsn: "Lynx Titan",
      bank: "none"
    });

    expect(context).toEqual({
      title: "You came from this profile",
      body: "Verify RuneLite sync for this RSN, then return to the player profile without losing account context.",
      cta: "Return to profile",
      href: "/u/Lynx%20Titan?from=plugin&bank=none"
    });
  });

  it("hides local release handoff from production player pages", () => {
    expect(shouldShowReleaseHandoff("development")).toBe(true);
    expect(shouldShowReleaseHandoff("test")).toBe(true);
    expect(shouldShowReleaseHandoff("production")).toBe(false);
  });

  it("does not tell players that enabling the plugin alone is enough to sync", () => {
    const checkerSource = readFileSync(join(process.cwd(), "src/components/plugin-sync-checker.tsx"), "utf8");
    const diagnosticsSource = readFileSync(join(process.cwd(), "src/lib/plugin-sync-diagnostics.ts"), "utf8");

    expect(checkerSource).not.toContain("plugin enabled, confirm the Sync URL");
    expect(checkerSource).not.toContain("if this finds your RSN, /next can use exact account state");
    expect(diagnosticsSource).not.toContain("Scapestack Sync enabled.");
    expect(checkerSource).toContain("enable “Auto-sync on login”");
    expect(checkerSource).toContain("if this finds your RSN, /next can use the verified payload");
    expect(checkerSource).toContain("which signals are verified, partial or missing");
    expect(checkerSource).toContain('if (status === "exact") return "Verified";');
    expect(checkerSource).not.toContain('if (status === "exact") return "Exact";');
    expect(checkerSource).toContain("/next payload coverage");
    expect(checkerSource).toContain("Session action queue");
    expect(checkerSource).toContain("ordered like an OSRS session checklist");
    expect(checkerSource).toContain("actionQueueForSyncedPlayer");
    expect(checkerSource).toContain("syncUrlsForOrigin(syncOrigin)");
    expect(checkerSource).not.toContain("LOCAL_SYNC_URL");
    expect(checkerSource).not.toContain("LOCAL_SYNC_CLAIM_URL");
    expect(diagnosticsSource).toContain("syncUrlsForOrigin");
    expect(diagnosticsSource).toContain("After Plugin Hub is live");
    expect(diagnosticsSource).toContain("side-load the local plugin");
    expect(diagnosticsSource).toContain("Enable “Auto-sync on login”");
    expect(diagnosticsSource).not.toContain("Install Scapestack Sync, then enable");
  });

  it("lets synced players copy a safe proof receipt without tokens or account data", () => {
    const checkerSource = readFileSync(join(process.cwd(), "src/components/plugin-sync-checker.tsx"), "utf8");

    expect(checkerSource).toContain("formatPluginSyncProof");
    expect(checkerSource).toContain("Copy proof");
    expect(checkerSource).toContain("Proof copied");
    expect(checkerSource).toContain('useState<"idle" | "copied" | "error">("idle")');
    expect(checkerSource).toContain("setManualProofText(proofText)");
    expect(checkerSource).toContain("Clipboard failed — copy sync proof manually");
    expect(checkerSource).toContain("Manual sync proof fallback for");
    expect(checkerSource).toContain("event.currentTarget.select()");
    expect(checkerSource).toContain("never includes tokens, bank, inventory, chat, screenshots or account login");
  });

  it("keeps bank handoff privacy explicit on the plugin bridge", () => {
    const bannerSource = readFileSync(join(process.cwd(), "src/components/plugin-bank-handoff-banner.tsx"), "utf8");

    expect(bannerSource).toContain("clearBankHandoffPayload(window)");
    expect(bannerSource).toContain("Clear handoff");
    expect(bannerSource).toContain("Browser-only handoff");
    expect(bannerSource).toContain("the plugin never receives your bank, inventory, equipment, screenshots, clicks or account login");
  });
});
