import Image from "next/image";
import { redirect } from "next/navigation";
import { HeroIntake } from "@/components/hero-intake";
import { buildHomepageProof } from "@/lib/homepage-proof";
import { playerPath } from "@/lib/player-route";
import { resolveViewerRsn } from "@/lib/viewer-account";
import bossContrast from "../../data/boss-contrast.json";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const viewerRsn = await resolveViewerRsn();
  if (viewerRsn) redirect(playerPath(viewerRsn));
  const proof = buildHomepageProof();
  const boss = proof.boss;
  // Only the renders that measured under 3:1 against the ground get the
  // brightness lift; the rim goes to all of them. Numbers in
  // data/boss-contrast.json, regenerated by scripts/measure-boss-contrast.mjs.
  const bossIsDark = (bossContrast.homepage as Record<string, { contrast: number } | undefined>)
    [boss.slug]?.contrast ?? 0;

  return (
    <main data-home-page="true" className="scape-page pb-2 pt-2 sm:px-8 sm:pb-10 sm:pt-10">
      <section className="home-hero relative mx-auto w-full min-w-0 max-w-[var(--width-page)] overflow-hidden">
        <div className="grid min-w-0 items-center sm:min-h-[32rem] sm:grid-cols-[minmax(0,32rem)_minmax(23.75rem,32.5rem)] sm:gap-8">
          <div className="relative z-10 min-w-0 max-w-[32rem] py-8 sm:py-12">
            {/* SPEC §3.5, split at the spec's own full stop. The sentence is
                written as one line; as one h1 it is three lines of display
                type and the hook is buried at the end of it. "Stop
                bankstanding." is the hook, and the rest is what happens
                instead — which is what a subhead is for. Same words, in the
                order the spec wrote them. */}
            <h1 className="max-w-[20ch] text-[length:var(--text-page)] font-extrabold! leading-[1.04] text-[var(--color-text)]">
              Stop bankstanding.
            </h1>
            <p className="mt-3 max-w-[52ch] text-[length:var(--text-body)] font-normal leading-relaxed text-[var(--color-text-secondary)]">
              Set a goal, and Scapestack tells you the next step every session — and sends you a Sunday recap of what you banked.
            </p>
            <div className="mt-4 min-w-0">
              <HeroIntake />
            </div>
          </div>

          <figure
            data-home-boss-subject="true"
            data-boss-dark={bossIsDark > 0 && bossIsDark < 3 ? "true" : undefined}
            className="pointer-events-none absolute -right-32 top-0 z-0 flex h-80 w-[26rem] flex-col items-center justify-end sm:relative sm:right-auto sm:h-[32rem] sm:w-auto"
          >
            <span className="relative flex h-full w-full items-end justify-center opacity-[0.16] sm:opacity-100">
              <span aria-hidden="true" className="boss-plate absolute inset-4" />
              <span aria-hidden="true" className="absolute bottom-8 h-10 w-[68%] rounded-[50%] bg-black/45 blur-xl" />
              <Image
                src={`/api/sprite/boss/${boss.slug}`}
                alt=""
                aria-hidden="true"
                width={boss.width}
                height={boss.height}
                priority
                sizes="(max-width: 639px) 420px, (max-width: 1199px) 40vw, 520px"
                className="boss-render relative z-10 h-[22rem] w-[26rem] object-contain object-bottom sm:h-[32rem] sm:w-[clamp(23.75rem,40vw,32.5rem)]"
              />
            </span>
            {/* Under the render, not over it. It was absolutely positioned at
                the figure's bottom edge, which was invisible while the boss
                was — the moment the rim made Phantom Muspah readable, the
                boss's feet landed on top of its own caption. */}
            <figcaption className="relative z-20 mt-2 whitespace-nowrap text-center text-[length:var(--text-micro)] font-normal text-[var(--color-text-muted)]">
              Today&apos;s boss · {boss.name}
            </figcaption>
          </figure>
        </div>

        <ul
          aria-label="What Scapestack checks"
          className="relative z-10 mt-3 grid grid-cols-3 border-y border-[var(--color-border)] py-3 text-center sm:mt-4 sm:py-4"
        >
          <li className="border-r border-[var(--color-border)] px-2">
            <strong className="block tabular-nums text-[length:var(--text-subject)] font-semibold text-[var(--color-data-level)]">{proof.bossesChecked}</strong>
            <span className="text-[length:var(--text-micro)] font-semibold text-[var(--color-text-muted)]">bosses checked</span>
          </li>
          <li className="border-r border-[var(--color-border)] px-2">
            <strong className="block tabular-nums text-[length:var(--text-subject)] font-semibold text-[var(--color-data-combat)]">{proof.questsTracked}</strong>
            <span className="text-[length:var(--text-micro)] font-semibold text-[var(--color-text-muted)]">quests tracked</span>
          </li>
          <li className="px-2">
            <strong className="block tabular-nums text-[length:var(--text-subject)] font-semibold text-[var(--color-data-xp)]">{proof.itemsPriced.toLocaleString("en-GB")}</strong>
            <span className="text-[length:var(--text-micro)] font-semibold text-[var(--color-text-muted)]">items priced</span>
          </li>
        </ul>
      </section>
    </main>
  );
}
