import Image from "next/image";
import { redirect } from "next/navigation";
import { HeroIntake } from "@/components/hero-intake";
import { buildHomepageProof } from "@/lib/homepage-proof";
import { playerPath } from "@/lib/player-route";
import { resolveViewerRsn } from "@/lib/viewer-account";
import bossContrast from "../../data/boss-contrast.json";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const viewerRsn = await resolveViewerRsn();
  if (viewerRsn) redirect(playerPath(viewerRsn));
  const proof = buildHomepageProof();
  const boss = proof.boss;
  // Only the renders that measured under 3:1 against the ground get the
  // brightness lift; the rim goes to all of them. Numbers in
  // data/boss-contrast.json, regenerated by scripts/measure-boss-contrast.mjs.
  const bossIsDark = (bossContrast.homepage as Record<string, { contrast: number } | undefined>)
    [boss.slug]?.contrast ?? 0;

  return (
    <main data-home-page="true" className="scape-page pb-2 pt-2 sm:px-8 sm:pb-10 sm:pt-10">
      <section className="home-hero relative mx-auto w-full min-w-0 max-w-[var(--width-page)] overflow-hidden">
        {/* REBRAND.md Section 7, direction C — the Field Ledger. The signature
            element is this column: a recessed panel with a studded title bar
            and a black tally footer, at the proportions an OSRS side panel
            actually has, with the boss standing behind it at full height.

            DOM order is boss-then-column, and that is the whole mobile fix.
            The direction was chosen because a 225px panel gets STRONGER at
            390px rather than collapsing — but the mockup put the boss behind
            the column, which at phone width clipped it off the top of the
            screen and failed Section 8's "an in-world device is visible above
            the fold". Ordering it first costs one `sm:order` pair and the
            boss is the first thing a phone sees. */}
        <div className="grid min-w-0 gap-6 sm:min-h-[34rem] sm:grid-cols-[minmax(0,29rem)_minmax(0,1fr)] sm:items-center sm:gap-10">
          <figure
            data-home-boss-subject="true"
            data-boss-dark={bossIsDark > 0 && bossIsDark < 3 ? "true" : undefined}
            className="relative order-1 mx-auto flex h-56 w-full max-w-[22rem] flex-col items-center justify-end sm:order-2 sm:h-[34rem] sm:max-w-none"
          >
            <span className="relative flex h-full w-full items-end justify-center">
              <span aria-hidden="true" className="boss-plate absolute inset-4" />
              <Image
                src={`/api/sprite/boss/${boss.slug}`}
                alt=""
                aria-hidden="true"
                width={boss.width}
                height={boss.height}
                priority
                sizes="(max-width: 639px) 352px, (max-width: 1199px) 40vw, 520px"
                className="boss-render relative z-10 h-full w-auto object-contain object-bottom"
              />
            </span>
            {/* A chat line, per direction C: the game says this sort of thing
                in cyan, so the boss's name is the only coloured word. */}
            <figcaption className="relative z-20 mt-2 whitespace-nowrap text-center text-[length:var(--text-micro)] font-normal text-[var(--stone-text-muted)]">
              Today&apos;s boss ·{" "}
              <span style={{ color: "var(--msg-info)" }}>{boss.name}</span>
            </figcaption>
          </figure>

          <div
            data-ledger-column="true"
            className="relative z-10 order-2 min-w-0 border-2 border-[var(--wood-700)] bg-[var(--stone-700)] sm:order-1"
            style={{
              borderRadius: "var(--radius-md)",
              boxShadow: "inset 1px 1px 0 var(--bevel-light), inset -1px -1px 0 var(--bevel-dark)"
            }}
          >
            <div
              className="flex items-center justify-between gap-2 border-b border-[var(--stone-900)] bg-[var(--stone-800)] px-3 py-2"
              style={{ boxShadow: "inset 0 1px 0 var(--bevel-light)" }}
            >
              <span aria-hidden="true" className="size-[3px] shrink-0 bg-[var(--stone-500)]" />
              <span className="font-[family-name:var(--font-display)] text-[length:var(--text-micro)] font-semibold uppercase tracking-[0.28em] text-[var(--gold-500)]">
                Scapestack
              </span>
              <span aria-hidden="true" className="size-[3px] shrink-0 bg-[var(--stone-500)]" />
            </div>

            <div className="px-4 py-5 sm:px-5 sm:py-6">
              <p className="eyebrow">An adventurer&apos;s tool</p>
              {/* SPEC §3.5, split at the spec's own full stop. "Stop
                  bankstanding." is the hook; the rest is what happens instead,
                  which is what a subhead is for. */}
              <h1 className="mt-2 max-w-[16ch] text-[length:var(--text-answer)] font-extrabold! leading-[1.06] text-[var(--stone-text)] sm:text-[length:var(--text-page)]">
                Stop bankstanding.
              </h1>
              <p className="mt-3 max-w-[44ch] text-[length:var(--text-body)] font-normal leading-relaxed text-[var(--stone-text-muted)]">
                Tell it your goal. It picks your next trip, tells you when to stop, and posts what you banked each Sunday.
              </p>
              <div className="mt-5 min-w-0">
                <HeroIntake />
              </div>
            </div>

            {/* The black tally bar. REBRAND F6 deleted the KPI strip; Section
                6.1 allows the numbers as flavour, and a tally bar is exactly
                where the game puts a total. The counts are Fraunces tabular,
                not Pixelify — §10.2. */}
            <div className="border-t border-[var(--stone-900)] bg-[var(--stone-900)] px-4 py-2 text-center text-[length:var(--text-micro)] font-normal text-[var(--stone-text-muted)]">
              The almanac holds{" "}
              <span className="text-[var(--stone-text)]" style={{ fontVariantNumeric: "tabular-nums lining-nums" }}>
                {proof.bossesChecked}
              </span>{" "}
              bosses and{" "}
              <span className="text-[var(--stone-text)]" style={{ fontVariantNumeric: "tabular-nums lining-nums" }}>
                {proof.questsTracked}
              </span>{" "}
              quests.
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
