// Which wiki page describes which thing we reason about.
//
// This is the only hand-kept part of the game data, and it is deliberately the
// smallest possible part: a name, not a number. Everything measurable comes
// from data/wiki/ via scripts/wiki-project.mjs.
//
// Ten encounters are absent on purpose. Raids, Barrows, Wintertodt, Tempoross,
// Guardians of the Rift, Moons of Peril, Grotesque Guardians and Demonic
// Gorillas are multi-NPC fights that no single monster infobox describes, so
// their numbers stay ours and stay in src/lib/bosses.ts with a reason attached.
// Manual: grotesque-guardians, demonic-gorillas, barrows, cox, tob, toa, wintertodt, tempoross, guardians-of-the-rift, moons-of-peril

export const BOSS_WIKI_PAGES = {
  "graardor": { page: "General Graardor" },
  "kree": { page: "Kree'arra" },
  "zilyana": { page: "Commander Zilyana" },
  "kril": { page: "K'ril Tsutsaroth" },
  "nex": { page: "Nex" },
  "callisto": { page: "Callisto" },
  "venenatis": { page: "Venenatis" },
  "vetion": { page: "Vet'ion" },
  "calvarion": { page: "Calvar'ion" },
  "spindel": { page: "Spindel" },
  "artio": { page: "Artio" },
  "scorpia": { page: "Scorpia" },
  "chaos-elemental": { page: "Chaos Elemental" },
  "chaos-fanatic": { page: "Chaos Fanatic" },
  "crazy-archaeologist": { page: "Crazy Archaeologist" },
  "king-black-dragon": { page: "King Black Dragon" },
  "kalphite-queen": { page: "Kalphite Queen" },
  "vorkath": { page: "Vorkath" },
  "zulrah": { page: "Zulrah" },
  "hydra": { page: "Alchemical Hydra" },
  "sire": { page: "Abyssal Sire" },
  "kraken": { page: "Kraken" },
  "cerberus": { page: "Cerberus" },
  "thermonuclear": { page: "Thermonuclear Smoke Devil" },
  "skotizo": { page: "Skotizo" },
  "mimic": { page: "The Mimic" },
  "hespori": { page: "Hespori" },
  "vardorvis": { page: "Vardorvis" },
  "leviathan": { page: "The Leviathan" },
  "duke-sucellus": { page: "Duke Sucellus" },
  "whisperer": { page: "The Whisperer" },
  "phantom-muspah": { page: "Phantom Muspah" },
  "galvek": { page: "Galvek" },
  "corp": { page: "Corporeal Beast" },
  "dks-rex": { page: "Dagannoth Rex" },
  "dks-supreme": { page: "Dagannoth Supreme" },
  "dks-prime": { page: "Dagannoth Prime" },
  "obor": { page: "Obor" },
  "bryophyta": { page: "Bryophyta" },
  "tzkal-zuk": { page: "TzKal-Zuk" },
  "tztok-jad": { page: "TzTok-Jad" },
  "giant-mole": { page: "Giant Mole" },
  "deranged-archaeologist": { page: "Deranged Archaeologist" },
  "sarachnis": { page: "Sarachnis" },
  "zalcano": { page: "Zalcano" },
  "araxxor": { page: "Araxxor" },
  "amoxliatl": { page: "Amoxliatl" },
  "hueycoatl": { page: "The Hueycoatl" },
  "fortis-colosseum": { page: "Sol Heredit" },
};

/**
 * Equipment we model. `version` is unnecessary here: infobox_bonuses carries no
 * version anchor, so the projection picks the strongest offensive row per page
 * and records how many variants it collapsed.
 */
export const GEAR_WIKI_PAGES = [
  "Abyssal whip",
  "Abyssal tentacle",
  "Blade of Saeldor",
  "Ghrazi rapier",
  "Osmumten's fang",
  "Scythe of vitur",
  "Bandos godsword",
  "Armadyl godsword",
  "Dragon claws",
  "Voidwaker",
  "Dragon scimitar",
  "Rune scimitar",
  "Elder maul",
  "Twisted bow",
  "Bow of Faerdhinen",
  "Zaryte crossbow",
  "Toxic blowpipe",
  "Blazing blowpipe",
  "Rune crossbow",
  "Karil's crossbow",
  "Dark bow",
  "Tonalztics of ralos",
  "Burning claws",
  "Soulreaper axe",
  "Twinflame staff",
  "Tumeken's shadow",
  "Sanguinesti staff",
  "Harmonised nightmare staff",
  "Trident of the seas",
  "Trident of the swamp",
  "Kodai wand",
  "Ancient sceptre",
  "Slayer helmet (i)",
  "Slayer helmet",
  "Helm of neitiznot",
  "Neitiznot faceguard",
  "Serpentine helm",
  "Torva full helm",
  "Masori mask (f)",
  "Masori mask",
  "Ancestral hat",
  "Virtus mask",
  "Void mage helm",
  "Void mage helm",
  "Void ranger helm",
  "Void melee helm",
  "Infernal cape",
  "Fire cape",
  "Imbued saradomin cape",
  "Imbued guthix cape",
  "Ava's assembler",
  "Masori assembler",
  "Ardougne cloak 4",
  "Amulet of torture",
  "Amulet of fury",
  "Necklace of anguish",
  "Occult necklace",
  "Amulet of rancour",
  "Amulet of glory",
  "Salve amulet(ei)",
  "Bandos chestplate",
  "Torva platebody",
  "Ancestral robe top",
  "Virtus robe top",
  "Masori body (f)",
  "Masori body",
  "Armadyl chestplate",
  "Fighter torso",
  "Elite void top",
  "Bandos tassets",
  "Torva platelegs",
  "Ancestral robe bottom",
  "Masori chaps (f)",
  "Masori chaps",
  "Armadyl chainskirt",
  "Elite void robe",
  "Barrows gloves",
  "Ferocious gloves",
  "Zaryte vambraces",
  "Black d'hide vambraces",
  "Void knight gloves",
  "Mithril gloves",
  "Primordial boots",
  "Pegasian boots",
  "Eternal boots",
  "Dragon boots",
  "Ranger boots",
  "Ultor ring",
  "Magus ring",
  "Venator ring",
  "Bellator ring",
  "Lightbearer",
  "Berserker ring (i)",
  "Berserker ring",
  "Archers ring (i)",
  "Archers ring",
  "Seers ring (i)",
  "Seers ring",
  "Brimstone ring",
  "Warrior ring (i)",
  "Warrior ring",
  "Avernic defender",
  "Dragon defender",
  "Elysian spirit shield",
  "Dragonfire shield",
  "Dragonfire ward",
  "Elidinis' ward (f)",
  "Dragon arrow",
  "Ruby dragon bolts (e)",
  "Diamond dragon bolts (e)",
  "Dragon dart",
  "Amethyst dart",
  "Rada's blessing 4",
  "Rada's blessing 3",
  "Rada's blessing 2",
];

// No wiki row: Virtus robe legs
